FROM  node:22

WORKDIR /app

COPY package*.json ./ 

RUN npm install
COPY . .

RUN npx prisma generate


RUN npx tsc --project tsconfig.converter.json 

CMD ["node","dist/converter/index.js"]